name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        model: ["TS100", "TS80", "TS80P", "Pinecil"]

    steps:
      - uses: actions/checkout@v2

      - name: chmod
        run: chmod +x setup.sh && chmod +x source/build.sh && sudo mkdir -p /build/cache && sudo chmod -R 777 /build

      - name: Cached compiler source files
        uses: actions/cache@v2.1.5
        env:
          cache-name: cache-compilers
        with:
          path: /build/cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-

      - name: setup
        run: ./setup.sh

      - name: build ${{ matrix.model }}
        run: cd source && ./build.sh -m ${{ matrix.model }}

      - name: copy license text
        run: |
          cp LICENSE source/Hexfile/LICENSE
          cp LICENSE_RELEASE.md source/Hexfile/LICENSE_RELEASE.md

      - name: Archive ${{ matrix.model }} artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.model }}
          path: |
            source/Hexfile/${{ matrix.model }}_*.hex
            source/Hexfile/${{ matrix.model }}_*.bin
            source/Hexfile/LICENSE
            source/Hexfile/LICENSE_RELEASE.md
          if-no-files-found: error

  check_formatting:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: chmod
        run: chmod +x setup.sh && chmod +x source/build.sh && sudo mkdir -p /build/cache && sudo chmod -R 777 /build

      - name: Cached compiler source files
        uses: actions/cache@v2.1.5
        env:
          cache-name: cache-compilers
        with:
          # we deliberately persist a cache folder forwards
          path: /build/cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}
          restore-keys: |
            ${{ runner.os }}-

      - name: setup
        run: ./setup.sh

      - name: Check formatting with clang-format
        run: cd source && make clean && make check-style
